
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiicps.h"

/*
* The configuration table for devices
*/

XIicPs_Config XIicPs_ConfigTable[] =
{
	{
		XPAR_PS7_I2C_0_DEVICE_ID,
		XPAR_PS7_I2C_0_BASEADDR,
		XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ
	}
};


