
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdmaps.h"

/*
* The configuration table for devices
*/

XDmaPs_Config XDmaPs_ConfigTable[] =
{
	{
		XPAR_PS7_DMA_NS_DEVICE_ID,
		XPAR_PS7_DMA_NS_BASEADDR
	},
	{
		XPAR_PS7_DMA_S_DEVICE_ID,
		XPAR_PS7_DMA_S_BASEADDR
	}
};


