#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jul 07 10:22:02 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 8425b4259e254a4c874600d534396b66 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L axi_bram_ctrl_v4_1_4 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_rp_osc_behav xil_defaultlib.tb_rp_osc xil_defaultlib.glbl -log elaborate.log"
xelab -wto 8425b4259e254a4c874600d534396b66 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L axi_bram_ctrl_v4_1_4 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_rp_osc_behav xil_defaultlib.tb_rp_osc xil_defaultlib.glbl -log elaborate.log

