/**
 * $Id$
 *
 * @brief Waterfall diagrem colormap, generated by Octave.
 *
 * @Author Jure Menart <juremenart@gmail.com>
 *         
 * (c) Red Pitaya  http://www.redpitaya.com
 *
 * This part of code is written in C programming language.
 * Please visit http://en.wikipedia.org/wiki/C_(programming_language)
 * for more details on the language used herein.
 */

#ifdef __COLMAP_H
#error "This file may be included only once!"
#else
#define __COLMAP_H

#include <stdint.h>

#define RP_WF_COL_R 1
#define RP_WF_COL_G 2
#define RP_WF_COL_B 3

uint8_t rp_wf_colmap[64][3] = { 
 { 0, 0, 128 },
 { 0, 0, 144 },
 { 0, 0, 160 },
 { 0, 0, 176 },
 { 0, 0, 192 },
 { 0, 0, 208 },
 { 0, 0, 225 },
 { 0, 0, 241 },
 { 0, 2, 255 },
 { 0, 18, 255 },
 { 0, 34, 255 },
 { 0, 51, 255 },
 { 0, 67, 255 },
 { 0, 83, 255 },
 { 0, 99, 255 },
 { 0, 115, 255 },
 { 0, 132, 255 },
 { 0, 148, 255 },
 { 0, 164, 255 },
 { 0, 180, 255 },
 { 0, 196, 255 },
 { 0, 212, 255 },
 { 0, 229, 255 },
 { 0, 245, 255 },
 { 6, 255, 249 },
 { 22, 255, 233 },
 { 38, 255, 217 },
 { 55, 255, 200 },
 { 71, 255, 184 },
 { 87, 255, 168 },
 { 103, 255, 152 },
 { 119, 255, 136 },
 { 136, 255, 119 },
 { 152, 255, 103 },
 { 168, 255, 87 },
 { 184, 255, 71 },
 { 200, 255, 55 },
 { 217, 255, 38 },
 { 233, 255, 22 },
 { 249, 255, 6 },
 { 255, 245, 0 },
 { 255, 229, 0 },
 { 255, 213, 0 },
 { 255, 196, 0 },
 { 255, 180, 0 },
 { 255, 164, 0 },
 { 255, 148, 0 },
 { 255, 132, 0 },
 { 255, 115, 0 },
 { 255, 99, 0 },
 { 255, 83, 0 },
 { 255, 67, 0 },
 { 255, 51, 0 },
 { 255, 34, 0 },
 { 255, 18, 0 },
 { 255, 2, 0 },
 { 241, 0, 0 },
 { 225, 0, 0 },
 { 208, 0, 0 },
 { 192, 0, 0 },
 { 176, 0, 0 },
 { 160, 0, 0 },
 { 144, 0, 0 },
 { 128, 0, 0 }
};

#endif //__COLMAP_H
