######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "/home/matej/WORK/red_pitaya/project/ahead/red_pitaya.srcs/sources_1/edk/system"
if { [xload new system.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z010
xset package clg400
xset speedgrade -1

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
