#!/bin/sh

source /opt/etc/network/config

echo -n "Network: "

# Configure static network configuraton if selected
[ "x$NETWORK" != "xstatic" ] && {
    echo "DHCP"
    echo "To change your network configuration, edit /opt/etc/network/config."
} || {
    echo ""

    # Discover ethernet service/adapter name
    ETH0=`connmanctl services | grep ethernet | sed -e 's'/.*ethernet_/ethernet_/'`
    [ "x$ETH0" == "x" ] && {
        echo "Wired ethernet adapter not found."
        exit 255;
    }

    NETMASK_STR=$NETMASK
    GATEWAY_STR=$GATEWAY

    [ "x$IP" == "x" ] && {
        echo "ERROR: Static network selected, but IP not defined."
        echo "Please edit /opt/etc/network/config to fix."
	exit 255;
    }
    [ "x$NETMASK" == "x" ] && {
        NETMASK_STR=default
    }
    [ "x$GATEWAY" == "x" ] && {
        GATEWAY_STR=none
    }

    echo "  IP:      $IP"
    echo "  NETMASK: $NETMASK_STR"
    echo "  GATEWAY: $GATEWAY_STR"

    connmanctl config $ETH0 --ipv4 manual $IP $NETMASK $GATEWAY
}
