#!/bin/sh


echo "Starting rcS..."

echo "++ Mounting filesystems"
mkdir -p /dev/pts
mkdir -p /dev/i2c
mount -a

# Check if SD card mounted, if not wait and try again
if ! grep -qs '/opt' /proc/mounts; then
	sleep 1
	mount -a
fi

# Create /tmp structure every time, since it resides in RAM
mkdir -p /tmp/log/nginx

# the device driver is not creating this node, so for now
# create the devcfg device node manually

if [ ! -e /dev/xdevcfg ]
then
	mknod /dev/xdevcfg c 259 0
fi

# Shortcut link to u-boot EEPROM
ln -s /sys/bus/i2c/devices/0-0050/eeprom /dev/eeprom

# Fix keys for SHH
chmod 600 `find /etc/ -name ssh_host_\*`

echo "++ Running all startup scripts"
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in `find /etc/init.d/ -name S\* | sort` ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done

# Set user's connman network configuration
/etc/init.d/connman-config

# Run IP discovery service
/opt/sbin/discovery

# Start user rcS script from SD card
OPT_RCS=/opt/etc/init.d/rcS
echo "Running user script from SD card ..."
if [ -f $OPT_RCS ]
then
    source $OPT_RCS
else
    echo "$OPT_RCS not found."
fi

# Print OS version info
cat /etc/motd
