#!/bin/sh


echo "Starting rcS..."

echo "++ Mounting filesystems"
mkdir -p /dev/pts
mkdir -p /dev/i2c
mount -a

# Create /tmp structure every time, since it resides in RAM
mkdir -p /tmp/log/nginx

# the device driver is not creating this node, so for now
# create the devcfg device node manually

if [ ! -e /dev/xdevcfg ]
then
	mknod /dev/xdevcfg c 259 0
fi

# Shortcut link to u-boot EEPROM
ln -s /sys/bus/i2c/devices/0-0050/eeprom /dev/eeprom

echo "++ Bringing up lo"
ifup lo

# Allow some time for the USB WiFi device to be detected.
sleep 1;

# Bring-up wlan0 before eth0 to avoid routing problems due to 192.168.1.100
# default IP being assigned to eth0 if no cable is plugged in or no reply
# is received from the DHCP.
# This way, even if wlan0 gets the IP in 192.168.1.x range (via DHCP), the
# routing tables will be OK.
if [ -e /opt/etc/network/wpa_supplicant.conf ]
then
	echo "++ Bringing up wlan0"
	ifup wlan0
fi

echo "++ Bringing up eth0"
ifup eth0


# Fix keys for SHH
chmod 600 `find /etc/ -name ssh_host_\*`

echo "++ Running all startup scripts"
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in `find /etc/init.d/ -name S\* | sort` ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done

if [ -x /opt/sbin/discovery ]
then
	echo "++ Starting Red Pitaya IP discovery"
	/opt/sbin/discovery
fi

# Start user rcS script from SD card
OPT_RCS=/opt/etc/init.d/rcS
echo "Running user script from SD card ..."
if [ -f $OPT_RCS ]
then
    source $OPT_RCS
else
    echo "$OPT_RCS not found."
fi

# Print OS version info
cat /etc/motd
