#!/bin/sh

echo "Starting rcS..."

export PATH_REDPITAYA=/opt/redpitaya

echo "++ Mounting filesystems"
mkdir -p /dev/pts
mount -a

# Check if SD card mounted, if not wait and try again
if ! grep -qs $PATH_REDPITAYA /proc/mounts; then
	sleep 1
	mount -a
fi

# Create /tmp structure every time, since it resides in RAM
mkdir -p /tmp/log/redpitaya_nginx
mkdir -p /tmp/ram

# Fix keys for SHH
chmod 600 `find /etc/ -name ssh_host_\*`

echo "++ Running all startup scripts"
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in `find /etc/init.d/ -name S\* | sort` ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done

# Set user's connman network configuration
/etc/init.d/connman-config

# Run IP discovery service
$PATH_REDPITAYA/sbin/discovery.sh

# Print OS version info
cat $PATH_REDPITAYA/version.txt
