#!/bin/sh

case "$1" in
        start)
                echo -n "Starting nginx ... "
                /bin/cp -f /opt/sbin/nginx /sbin
                /sbin/nginx -p /opt/www
                echo "done."
                ;;
        stop)
                echo -n "Stopping nginx ..."
                killall nginx
                echo "done."
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "usage: $0 {start|stop|restart}"
                ;;
esac
