#!/bin/sh

source /etc/profile

case "$1" in
        start)
                echo -n "Starting nginx ... "
                LD_LIBRARY_PATH=$PATH_REDPITAYA/lib $PATH_REDPITAYA/sbin/nginx -p $PATH_REDPITAYA/www
                echo "done."
                ;;
        stop)
                echo -n "Stopping nginx ..."
                killall nginx
                echo "done."
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "usage: $0 {start|stop|restart}"
                ;;
esac
