#!/bin/sh

case "$1" in
        start)
                echo -n "Starting SPCI server ... "
                #demonize -p /var/run/scpi.pid -l /var/run/scpi.pid LD_LIBRARY_PATH=/opt/redpitaya/lib /opt/redpitaya/bin/scpi-server
                /var/run/scpi.pid LD_LIBRARY_PATH=/opt/redpitaya/lib /opt/redpitaya/bin/scpi-server &
                echo "done."
                ;;
        stop)
                echo -n "Stopping SCPI server ..."
                killall scpi-server
                echo "done."
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "usage: $0 {start|stop|restart}"
                ;;
esac
