#!/usr/bin/env python3
"""Generate rp_ram_profiles.h from the board profiles in rp-api/api-hw-profiles.

The FSBL needs to know which hw_rev strings mean a 32-bit DDR bus (1 GB).
That mapping already exists in the ecosystem sources:

  common.cpp   maps a lower-cased hw_rev string to a getProfile_* function
  stem_*.cpp   defines the profile struct, including .ramMB

Rather than duplicating the list by hand this script joins the two and emits a
header for the FSBL. Any parsing failure is fatal: a silently empty list would
turn every 1 GB board into a 512 MB one.
"""

import argparse
import re
import sys
from pathlib import Path

# {"stem_250-12_v1.2", getProfile_STEM_250_12_v1_2},
MAP_ENTRY = re.compile(r'\{\s*"([^"]+)"\s*,\s*(getProfile_\w+)\s*\}')

# profiles_t stem_250_12_v1_2 = {.boardModel = ...
PROFILE_VAR = re.compile(r'^\s*profiles_t\s+(\w+)\s*=\s*\{', re.M)

RAM_FIELD = re.compile(r'\.ramMB\s*=\s*(\d+)')

# profiles_t* getProfile_STEM_250_12_v1_2() { ... return &stem_250_12_v1_2; }
GETTER_RETURN = re.compile(r'(getProfile_\w+)\s*\([^)]*\)\s*\{(.*?)\n\}', re.S)
RETURN_VAR = re.compile(r'return\s*&?\s*(\w+)')


def fail(msg):
    sys.exit(f"gen_ram_profiles: {msg}")


def parse_profile_map(common_cpp):
    """hw_rev string (lower case) -> getProfile_* name."""
    text = common_cpp.read_text(errors="replace")
    entries = MAP_ENTRY.findall(text)
    if not entries:
        fail(f"no profileMap entries found in {common_cpp}")
    return {key: getter for key, getter in entries}


def parse_profile_ram(src_dir):
    """getProfile_* name -> ramMB."""
    ram_by_getter = {}
    for path in sorted(src_dir.glob("stem_*.cpp")):
        text = path.read_text(errors="replace")

        ram_by_var = {}
        for m in PROFILE_VAR.finditer(text):
            var = m.group(1)
            ram = RAM_FIELD.search(text, m.end())
            if ram is None:
                fail(f"{path.name}: no .ramMB for profile '{var}'")
            ram_by_var[var] = int(ram.group(1))

        if not ram_by_var:
            fail(f"{path.name}: no profiles_t definition found")

        for getter, body in GETTER_RETURN.findall(text):
            ret = RETURN_VAR.search(body)
            if ret is None:
                continue
            var = ret.group(1)
            if var in ram_by_var:
                ram_by_getter[getter] = ram_by_var[var]

    if not ram_by_getter:
        fail(f"no getProfile_* functions resolved in {src_dir}")
    return ram_by_getter


def build_list(profile_map, ram_by_getter, threshold):
    big, unresolved = [], []
    for hw_rev, getter in sorted(profile_map.items()):
        ram = ram_by_getter.get(getter)
        if ram is None:
            unresolved.append((hw_rev, getter))
            continue
        if ram > threshold:
            big.append((hw_rev, ram))

    if unresolved:
        lines = "\n".join(f"  {k} -> {g}" for k, g in unresolved)
        fail(f"could not resolve .ramMB for:\n{lines}")
    if not big:
        fail(f"no profile with ramMB > {threshold} - the mapping looks broken")
    return big


def emit(big, out_path):
    lines = [
        "/* Generated by gen_ram_profiles.py - do not edit.",
        " * Source of truth: rp-api/api-hw-profiles (profileMap + .ramMB).",
        " * hw_rev values whose board carries a 32-bit DDR bus (1 GB).",
        " */",
        "#ifndef RP_RAM_PROFILES_H",
        "#define RP_RAM_PROFILES_H",
        "",
        "#define RP_RAM_PROFILES_AVAILABLE 1",
        "",
        "static const char *const rp_hw_rev_1gb[] = {",
    ]
    for hw_rev, ram in big:
        lines.append(f'    "{hw_rev}", /* {ram} MB */')
    lines += [
        "};",
        "",
        f"#define RP_HW_REV_1GB_COUNT {len(big)}u",
        "",
        "#endif /* RP_RAM_PROFILES_H */",
        "",
    ]
    out_path.write_text("\n".join(lines))


def check_uboot_script(path, big, threshold):
    """The boot script has to mark the same boards as the profiles do.

    It branches on hw_rev anyway, so the size is set there rather than probed;
    this keeps the two lists from drifting apart.
    """
    text = Path(path).read_text(errors="replace")
    expected = {hw_rev for hw_rev, _ in big}
    marked = set()

    block = re.compile(r"if test \$\{hw_rev\} == '([^']+)'\s*\nthen\n(.*?)\nfi",
                       re.S)
    for m in block.finditer(text):
        if "setenv memsize  0x40000000" in m.group(2):
            marked.add(m.group(1).lower())

    missing = expected - marked
    extra = marked - expected
    if missing or extra:
        fail(f"{path} disagrees with the profiles:\n"
             f"  missing memsize: {sorted(missing)}\n"
             f"  unexpected memsize: {sorted(extra)}")
    print(f"gen_ram_profiles: {path} marks all {len(expected)} "
          f"boards above {threshold} MB")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profiles-dir", required=True,
                    help="path to rp-api/api-hw-profiles/src")
    ap.add_argument("--out", required=True, help="output rp_ram_profiles.h")
    ap.add_argument("--check-uboot-script",
                    help="verify this boot script marks the same boards")
    ap.add_argument("--threshold", type=int, default=512,
                    help="ramMB above this means a 32-bit DDR bus")
    args = ap.parse_args()

    src_dir = Path(args.profiles_dir)
    common = src_dir / "common.cpp"
    if not common.is_file():
        fail(f"{common} not found")

    profile_map = parse_profile_map(common)
    ram_by_getter = parse_profile_ram(src_dir)
    big = build_list(profile_map, ram_by_getter, args.threshold)

    emit(big, Path(args.out))
    if args.check_uboot_script:
        check_uboot_script(args.check_uboot_script, big, args.threshold)
    print(f"gen_ram_profiles: {len(profile_map)} hw_rev entries, "
          f"{len(big)} with > {args.threshold} MB")
    for hw_rev, ram in big:
        print(f"  {hw_rev}: {ram} MB")


if __name__ == "__main__":
    main()
