
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xttcps.h"

/*
* The configuration table for devices
*/

XTtcPs_Config XTtcPs_ConfigTable[] =
{
	{
		XPAR_PS7_TTC_0_DEVICE_ID,
		XPAR_PS7_TTC_0_BASEADDR,
		XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_1_DEVICE_ID,
		XPAR_PS7_TTC_1_BASEADDR,
		XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_2_DEVICE_ID,
		XPAR_PS7_TTC_2_BASEADDR,
		XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ
	}
};


