#!/bin/sh
#
# OS/Ecosystem post install script
# Executed by Bazaar script after release 0.92
#
# Assume RW mounted SD card (/opt)

# Remove scripts, which have been moved to ramdisk
rm -f /opt/sbin/bazaar
rm -f /opt/sbin/ro
rm -f /opt/sbin/rw
rm -f /opt/bin/bc
rm -f /opt/bin/lantiq_mdio

