
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xscugic.h"

/*
* The configuration table for devices
*/

XScuGic_Config XScuGic_ConfigTable[] =
{
	{
		XPAR_PS7_SCUGIC_0_DEVICE_ID,
		XPAR_PS7_SCUGIC_0_BASEADDR,
		XPAR_PS7_SCUGIC_0_DIST_BASEADDR
	}
};


