#!/bin/bash
#
# Emit the page's font settings as CSS, served as /nm_fonts.css and loaded after
# css/nm.css so it overrides the defaults there.
#
# Settings come from
#
#     /home/redpitaya/.config/network_manager.conf
#
# a plain key=value file. Nothing there is required; anything missing or invalid
# falls back to the built-in default, so an absent file is the normal case
# rather than an error.
#
#     # base font size in px for the Network Manager page, 11 to 24
#     # (default 14; anything outside the range is ignored)
#     font_size=16
#
#     # optional font stack for the page's proportional text
#     font_family=Roboto, Arial, sans-serif
#
#     # optional font stack for values and logs
#     font_mono=Menlo, Consolas, monospace
#
# Only font_size feeds the rest of the scale: every other size on the page is
# derived from it with calc(), so one number moves the whole page and nothing
# drifts out of proportion.
#
# CSS is emitted rather than JSON on purpose. Applying sizes from JavaScript
# means the page paints once at the default and then jumps; a stylesheet is
# applied before the first paint.

CONF=/home/redpitaya/.config/network_manager.conf

FS_DEFAULT=14
FS=$FS_DEFAULT
FAMILY=''
MONO=''

read_key() {
    # last assignment wins, comments and surrounding whitespace ignored
    sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\(.*\)$/\1/p" "$CONF" 2>/dev/null \
        | sed 's/[[:space:]]*$//' | grep -v '^$' | tail -1
}

if [ -r "$CONF" ]; then
    V=$(read_key font_size)
    # 11..24. Below 11 the derived captions hit their floor and the scale stops
    # being a scale; above 24 the section rail no longer fits its column. A value
    # outside that is more likely a typo than an intent, so it is rejected and
    # the default used, rather than squashed into range where the page would
    # silently not honour the file.
    case "$V" in
        1[1-9]|2[0-4]) FS=$V ;;
    esac

    # Font stacks are echoed into a stylesheet. Keep only what a stack can
    # legitimately contain - letters, digits, spaces, commas, hyphens, dots and
    # quotes - and drop the value entirely if anything else was in it. A
    # whitelist beats stripping bad characters: stripping turns
    # "Arial; } body {" into a nonsense family that silently renders wrong,
    # where rejecting says the setting was ignored.
    keep_stack() {
        local v="$1"
        [ -n "$v" ] || return 0
        case "$v" in
            *[!A-Za-z0-9\ ,.\'\"-]*) return 0 ;;
        esac
        printf '%s' "$v" | cut -c1-200
    }

    FAMILY=$(keep_stack "$(read_key font_family)")
    MONO=$(keep_stack "$(read_key font_mono)")
fi

echo "/* generated by scripts/get_ui_config.sh */"
echo "/* source: $CONF $( [ -r "$CONF" ] && echo '(read)' || echo '(absent, using defaults)' ) */"
echo ":root {"
echo "    --nm-fs: ${FS}px;"
[ -n "$FAMILY" ] && echo "    --nm-family: $FAMILY;"
[ -n "$MONO" ]   && echo "    --nm-mono: $MONO;"
echo "}"

# --nm-family has no default in nm.css: with nothing configured the page keeps
# inheriting the suite's font, which is what it should do.
if [ -n "$FAMILY" ]; then
    echo ".nm-shell, .nm-main { font-family: var(--nm-family); }"
fi

exit 0
