#!/bin/bash
#
# Write the HTTPS settings and regenerate the nginx fragments they describe.
#
#     https_apply.sh <enabled 0|1> <port> <redirect 0|1> [cert_source]
#
# cert_source is optional; left out, whatever is already configured stays.
#
# The new fragments are checked with "nginx -t" and the old ones put back if
# the test fails -- a configuration nginx refuses takes the web interface off
# the network entirely.

set -u

SELF_DIR=$(dirname "$0")
# shellcheck source=https_lib.sh
. "$SELF_DIR/https_lib.sh"

die() { echo "error: $1" >&2; exit "${2:-1}"; }

ENABLED="${1:-}"
PORT="${2:-}"
REDIRECT="${3:-}"
SOURCE="${4:-}"

case "$ENABLED" in 0|1) ;; *) die "usage: https_apply.sh <enabled 0|1> <port> <redirect 0|1> [cert_source]" 2 ;; esac
case "$REDIRECT" in 0|1) ;; *) die "redirect must be 0 or 1" 2 ;; esac
is_port "$PORT" || die "port must be a number between 1 and 65535" 2
if [ -n "$SOURCE" ]; then
    case "$SOURCE" in self|upload|acme) ;; *) die "unknown certificate source '$SOURCE'" 2 ;; esac
fi

https_load
[ -n "$SOURCE" ] && HTTPS_CERT_SOURCE=$SOURCE
cert_paths

if [ "$ENABLED" = "1" ]; then
    # Without a domain, cert_paths falls back to the self-signed pair -- which
    # would serve one certificate while the settings claim another.
    if [ "$HTTPS_CERT_SOURCE" = "acme" ] && [ -z "$HTTPS_ACME_DOMAIN" ]; then
        die "no Let's Encrypt certificate has been requested yet"
    fi
    ssl_module_available || die "this nginx build has no SSL module; rebuild the ecosystem with --with-http_ssl_module"
    [ -r "$CERT_FILE" ] || die "no certificate at $CERT_FILE -- generate, upload or request one first"
    [ -r "$KEY_FILE" ]  || die "no private key at $KEY_FILE -- generate, upload or request one first"
fi

mkdir -p "$FRAG_DIR" "$FRAG80_DIR" "$RP_ETC" || die "could not create $RP_ETC"

exec 9>"$LOCK_FILE"
if ! flock -w 10 9; then
    die "could not acquire the network config lock within 10s (another apply in progress?)" 3
fi

# Keep the current fragments so a failed test can be undone.
BACKUP=$(mktemp -d /run/rp-https-backup.XXXXXX 2>/dev/null || mktemp -d /tmp/rp-https-backup.XXXXXX) \
    || die "could not create a backup directory"
cp -f "$FRAG_SSL"      "$BACKUP/https.conf"    2>/dev/null
cp -f "$FRAG_REDIRECT" "$BACKUP/redirect.conf" 2>/dev/null

restore() {
    if [ -f "$BACKUP/https.conf" ]; then cp -f "$BACKUP/https.conf" "$FRAG_SSL"; else rm -f "$FRAG_SSL"; fi
    if [ -f "$BACKUP/redirect.conf" ]; then cp -f "$BACKUP/redirect.conf" "$FRAG_REDIRECT"; else rm -f "$FRAG_REDIRECT"; fi
    rm -rf "$BACKUP"
}

if [ "$ENABLED" = "1" ]; then
    cat > "$FRAG_SSL" <<EOF
# Generated by network_manager/scripts/https_apply.sh -- edits are overwritten
# the next time the HTTPS section is applied.
# No "http2 on": the shared body sets keepalive_timeout 0, and over HTTP/2 that
# makes nginx send GOAWAY after the first request, so a browser loading a page
# gets ERR_HTTP2_SERVER_REFUSED_STREAM on every other resource.
server {
    listen $PORT ssl;
    listen [::]:$PORT ssl;

    ssl_certificate     $CERT_FILE;
    ssl_certificate_key $KEY_FILE;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:2m;
    ssl_session_timeout 1h;

    include $NGINX_PREFIX/conf/server_common.conf;
}
EOF
else
    rm -f "$FRAG_SSL"
fi

if [ "$ENABLED" = "1" ] && [ "$REDIRECT" = "1" ]; then
    # $host has no port, so a non-default one is appended here.
    if [ "$PORT" = "443" ]; then TARGET='https://$host$request_uri'; else TARGET="https://\$host:$PORT\$request_uri"; fi

    # "if" at server level is safe with "return". The challenge path is
    # excluded so a certificate can still be renewed while the redirect is on.
    #
    # 302, not 301: browsers cache a permanent redirect and keep sending
    # themselves to https long after this setting is turned off, which looks
    # exactly like a board that stopped answering.
    cat > "$FRAG_REDIRECT" <<EOF
# Generated by network_manager/scripts/https_apply.sh -- edits are overwritten
# the next time the HTTPS section is applied.
if (\$request_uri !~* "^/\\.well-known/acme-challenge/") {
    return 302 $TARGET;
}
EOF
else
    rm -f "$FRAG_REDIRECT"
fi

# Whatever the boot guard once set aside is now superseded by this apply.
rm -f "$FRAG_SSL.disabled" "$FRAG_REDIRECT.disabled" 2>/dev/null

TEST_OUT=$(nginx_test)
if [ $? -ne 0 ]; then
    restore
    echo "error: nginx rejected the new configuration, nothing was changed" >&2
    echo "$TEST_OUT" >&2
    exit 4
fi

# Written only after the test passed: the file describes what nginx runs.
UMASK_OLD=$(umask)
umask 077
cat > "$HTTPS_CONF" <<EOF
# Red Pitaya HTTPS settings, written by the Network Manager.
# See network_manager/scripts/https_lib.sh for the accepted values.
enabled=$ENABLED
port=$PORT
redirect=$REDIRECT
cert_source=$HTTPS_CERT_SOURCE
acme_domain=$HTTPS_ACME_DOMAIN
acme_email=$HTTPS_ACME_EMAIL
acme_staging=$HTTPS_ACME_STAGING
EOF
umask "$UMASK_OLD"

RELOAD_OUT=$(nginx_reload)
if [ $? -ne 0 ]; then
    # The configuration passed its test, so the fragments stay: a restart of
    # the service picks them up.
    rm -rf "$BACKUP"
    echo "error: nginx did not reload: $RELOAD_OUT" >&2
    exit 5
fi

rm -rf "$BACKUP"

if [ "$ENABLED" = "1" ]; then
    echo "OK https enabled on port $PORT (certificate: $HTTPS_CERT_SOURCE, redirect: $REDIRECT)"
else
    echo "OK https disabled"
fi
exit 0
