#!/bin/sh

# User startup script

# Uncomment the following and set a proper <DNS_IP> if your
# network configuration is static.
# echo "nameserver <DNS_IP>" > /tmp/resolv.conf

#TODO: This is a temporay solutio, fix to include librp in /lib dir on system boot.
rw
#Copy scpi lib
cp /opt/lib/* /lib
ro

echo "Feel free to add custom initialization commands here."