INSTALL_DIR ?= .
BINARY_FILES = production_testing_script.sh calibration_script.sh delete_MAC.sh
TEXT_FILES = environment_parameters.txt

all:

clean:

install:
	mkdir -p $(INSTALL_DIR)/bin
	cp $(BINARY_FILES) $(INSTALL_DIR)/bin
	cp $(TEXT_FILES) $(INSTALL_DIR)
