
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xscutimer.h"

/*
* The configuration table for devices
*/

XScuTimer_Config XScuTimer_ConfigTable[] =
{
	{
		XPAR_PS7_SCUTIMER_0_DEVICE_ID,
		XPAR_PS7_SCUTIMER_0_BASEADDR
	}
};


