
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartps.h"

/*
* The configuration table for devices
*/

XUartPs_Config XUartPs_ConfigTable[] =
{
	{
		XPAR_PS7_UART_0_DEVICE_ID,
		XPAR_PS7_UART_0_BASEADDR,
		XPAR_PS7_UART_0_UART_CLK_FREQ_HZ,
		XPAR_PS7_UART_0_HAS_MODEM
	}
};


